name: Build/release
on:
  push:
    tags: 
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
      
      - name: Building .Net Backend
        run: dotnet publish -r win-x64 ./LettuceIo.Dotnet --output ./LettuceIO
      
      - name: Download NPM Dependencies
        run: npm install
      
      - name: Build Electron
        run: npm run electron:build
  
#       - name: Upload Release
#         uses: actions/upload-release-asset@v1.0.2
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.get_release_url.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
#           asset_path: ./dist_electron/lettuce Setup *.exe
#           asset_name: lettuce Setup *.exe
#           asset_content_type: application/octet-stream
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist_electron/lettuce Setup *.exe
          asset_name: dist_electron/lettuce Setup *.exe
          tag: ${{ github.ref }}
