name: Build/release
on:
  push:
    tags: 
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
      
      - name: Building .Net Backend
        run: dotnet publish -r win-x64 ./LettuceIo.Dotnet --output ./LettuceIO
      
      - name: Download NPM Dependencies
        run: npm install
      
      - name: Build Electron
        run: npm run electron:build
      
